twolink:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 2000  

# Effort Controllers ---------------------------------------
  joint_1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_1
# Effort Controllers ---------------------------------------
  joint_2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_2

# Position Controllers ---------------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 10.0, i: 1.0, d: 1.0}
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 10.0, i: 1.0, d: 10.0}
